; Zone file for {{ $domain->name }}
; Generated by FreePanel
; Serial: {{ $zone->serial }}

$TTL 86400
$ORIGIN {{ $domain->name }}.

@foreach($records as $record)
@if($record->type === 'SOA')
; SOA Record
@   IN  SOA {{ $zone->ns1 }}. admin.{{ $domain->name }}. (
        {{ $zone->serial }}    ; Serial
        {{ $zone->refresh }}   ; Refresh
        {{ $zone->retry }}     ; Retry
        {{ $zone->expire }}    ; Expire
        {{ $zone->minimum }}   ; Minimum TTL
    )

@elseif($record->type === 'NS')
; Nameserver Records
{{ $record->name === '@' ? '@' : $record->name }}   {{ $record->ttl }}  IN  NS  {{ $record->content }}.
@elseif($record->type === 'A')
; A Records
{{ $record->name === '@' ? '@' : $record->name }}   {{ $record->ttl }}  IN  A   {{ $record->content }}
@elseif($record->type === 'AAAA')
; AAAA Records
{{ $record->name === '@' ? '@' : $record->name }}   {{ $record->ttl }}  IN  AAAA    {{ $record->content }}
@elseif($record->type === 'CNAME')
; CNAME Records
{{ $record->name }}   {{ $record->ttl }}  IN  CNAME   {{ $record->content }}.
@elseif($record->type === 'MX')
; MX Records
{{ $record->name === '@' ? '@' : $record->name }}   {{ $record->ttl }}  IN  MX  {{ $record->priority }}  {{ $record->content }}.
@elseif($record->type === 'TXT')
; TXT Records
{{ $record->name === '@' ? '@' : $record->name }}   {{ $record->ttl }}  IN  TXT "{{ $record->content }}"
@elseif($record->type === 'SRV')
; SRV Records
{{ $record->name }}   {{ $record->ttl }}  IN  SRV {{ $record->priority }} {{ $record->content }}
@elseif($record->type === 'CAA')
; CAA Records
{{ $record->name === '@' ? '@' : $record->name }}   {{ $record->ttl }}  IN  CAA {{ $record->content }}
@endif
@endforeach
